# Generated by Django 5.0.6 on 2024-06-25 17:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_mainposts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mainPosts',
            new_name='MainPost',
        ),
        migrations.AlterModelOptions(
            name='mainpost',
            options={'verbose_name': 'Main Post', 'verbose_name_plural': 'Main Posts'},
        ),
    ]
